finish personal portfolio - Add Portfolio and skills
AsciencioAlex/Personal-Portfolio pull request #2
Opened 2023-06-03 20:16 UTC by AsciencioAlex

Creation of about me page
Addition of skills and portfolio page
Addition of Resume
Add of Frameworks and Languages section

2023-06-03 22:24 UTC, Bantealem requested changes
Hi @AsciencioAlex , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [x] Correct Github flow
- [x] No Linters Error
- [x] Professional README 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 22:24 UTC, Bantealem commented on index.html
> +						<p class="description-main">A daily selection of privately personalized reads; no accounts
Great job. Please make sure your design is the same as Figma design.
Your design

![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/0f8f1c79-896e-478a-9b54-8cf1b6bebb86)

Figma design

![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/dfd5dc28-9651-4b07-ae7b-3ded19340f8c)

2023-06-03 22:24 UTC, Bantealem commented on index.html
> +							</li>
Please make sure your design is the same as Figma design.
Your design

![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/5bad4e69-0924-47e4-be0a-238a58be320e)
 Figma design

![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/a6300e87-d7ff-4fdc-939d-7c943737cf68)

2023-06-03 22:24 UTC, Bantealem commented on index.html
> +					<ul class="social__icons flex-row align-center">
Please make sure you used the correct font-color from the FGima design
Your design
![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/2e955db2-5ad5-4906-bfc0-2a38899a5bb5)
Figma design
![image](https://github.com/AsciencioAlex/Personal-Portfolio/assets/101523582/06a6f85b-d12d-464c-aa58-c656344efeee)

2023-06-04 04:19 UTC, Cabraham1 approved these changes
Hi @AsciencioAlex  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-04 04:24 UTC, merged